CUDA_VISIBLE_DEVICES=0,1 python main.py \
    --output_dir=./ \
    --model_type=roberta \
    --config_name=microsoft/codebert-base \
    --model_name_or_path=microsoft/codebert-base \
    --tokenizer_name=roberta-base \
    --do_train \
    --train_data_file=../../data/code_search/train.jsonl \
    --eval_data_file=../../data/code_search/valid.jsonl \
    --test_data_file=../../data/code_search/test.jsonl \
    --epoch 2 \
    --block_size 256 \
    --train_batch_size 32 \
    --eval_batch_size 64 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456 2>&1| tee train.log

CUDA_VISIBLE_DEVICES=0,1 python main.py \
    --output_dir=./ \
    --model_type=roberta \
    --config_name=microsoft/codebert-base \
    --model_name_or_path=microsoft/codebert-base \
    --tokenizer_name=roberta-base \
    --do_eval \
    --do_test \
    --train_data_file=../../data/code_search/train.jsonl \
    --eval_data_file=../../data/code_search/valid.jsonl \
    --test_data_file=../../data/code_search/test.jsonl \
    --epoch 2 \
    --block_size 256 \
    --train_batch_size 32 \
    --eval_batch_size 64 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456 2>&1| tee test.log